CNN:
  conv1:
    in_channels: 4
    out_channels: 48
    kernel_size: 15
    stride: 3
    padding: 2
  relu1: None
  conv2:
    in_channels: 48
    out_channels: 96
    kernel_size: 5
    stride: 1
    padding: 2
  maxpool:
    kernel_size: 2
  dropout1: 0.25
  flatten: None
  fc1:
    in_features: 3456
    out_features: 408
  relu2: None
  dropout2: 0.5
  fc2:
    in_features: 408
    out_features: 25
  softmax: None

RNN:
  lstm:
    input_size: 4
    hidden_size: 128
    num_layers: 2
    batch_first: True
  fc:
    in_features: 128
    out_featrues: 25

fc1:
  in_features: 50
  out_features: 4
relu: None
fc2:
  in_features: 4
  out_features: 2
softmax: None
  
batch_size: 5
shuffle: True
num_workers: 4