CNN:
  conv1:
    in_channels: 4
    out_channels: 48
    kernel_size: 15
    stride: 3
    padding: 2
  relu1: None
  conv2:
    in_channels: 48
    out_channels: 96
    kernel_size: 5
    stride: 1
    padding: 2
  maxpool:
    kernel_size: 2
  dropout1:
    p: 0.25
  flatten: None
  fc1:
    in_features: 3456
    out_features: 408
  relu2: None
  dropout2:
    p: 0.5
  fc2:
    in_features: 408
    out_features: 25
  softmax: None

RNN:
  lstm:
    input_size: 4
    hidden_size: 128
    num_layers: 2
    batch_first: True
  fc:
    in_features: 128
    out_features: 25

fc1:
  in_features: 50
  out_features: 6
relu: None
fc2:
  in_features: 6
  out_features: 3
softmax: None

test_size: 0.1
num_shards: 75
monitor_frequency: 500
batch_size: 5
shuffle: True
num_workers: 4

num_epochs: 3
learning_rate: 0.001
optimizer: adam
loss: crossentropy
validation_size: 1000